#preload = /home/parker/Pictures/pexels-chaitaastic-3722910.jpg
#wallpaper = ,/home/parker/Pictures/pexels-chaitaastic-3722910.jpg

splash = false

wallpaper {
    monitor = eDP-1
    path = /home/parker/Downloads/background.jpg
    fit_mode = cover
}
