# set leader
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# overwrite pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# base style
set -g status-style bg=#475258,fg=#d3c6aa
set -g status-left '#[bg=#dbbc7f,fg=#475258,bold] #S '
set -g status-right '#[bg=#dbbc7f,fg=#475258,bold] %H:%M '
set -g window-status-current-style bg=#dbbc7f,fg=#475258,bold
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g status-left-length 20

# Pane borders
set -g pane-border-style fg=#475258
set -g pane-active-border-style fg=#dbbc7f
